In [1]:
#hashing
print("hash for 21 is ",hash(21))
print("hash for 231.32 is ",hash(231.32))
print("hash for python is ",hash("python"))

hash for 21 is  21
hash for 231.32 is  737869762948366567
hash for python is  -5810627750905724907


In [2]:
print(hash("python"))

-5810627750905724907


In [3]:
print(hash("python"))

-5810627750905724907


In [4]:
hash("Python")

693545773853481974

In [5]:
tuple_val=(2,5,6,4,7)
print(str(hash(tuple_val)))

-185619385024537483


In [6]:
#list has no hash value

In [7]:
#timeit
#its code will be execute and its  executed and its execution time will be returned

In [8]:
import timeit
def test(n):
    return sum(range(n))
n=1000
print(timeit.timeit(lambda: test(n),number=100))

0.0009698000000000206


In [9]:
%timeit [num for num in range(100)]

4.52 µs ± 397 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
%timeit -r5 -n100 [num for num in range(100)]

4.82 µs ± 628 ns per loop (mean ± std. dev. of 5 runs, 100 loops each)


In [11]:
%%timeit -r5 -n1000
for i in range(100):
    n=i**2 
    m=i**3
    o=abs(i)

40.8 µs ± 2.4 µs per loop (mean ± std. dev. of 5 runs, 1000 loops each)


In [12]:
%%timeit -n 100
import numpy as np
a=np.arange(n)
np.sum(a)

The slowest run took 234.06 times longer than the fastest. This could mean that an intermediate result is being cached.
138 µs ± 326 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [13]:
from sklearn.feature_extraction.text import CountVectorizer
corpus=["this is the first document.",
       "this is the second document.",
       "and this is the third one.",
       "is this the first first document?"]
cvectorizer=CountVectorizer()
x=cvectorizer.fit_transform (corpus)
print(cvectorizer.vocabulary_)
print(x)
print(x.shape)

{'this': 8, 'is': 3, 'the': 6, 'first': 2, 'document': 1, 'second': 5, 'and': 0, 'third': 7, 'one': 4}
  (0, 8)	1
  (0, 3)	1
  (0, 6)	1
  (0, 2)	1
  (0, 1)	1
  (1, 8)	1
  (1, 3)	1
  (1, 6)	1
  (1, 1)	1
  (1, 5)	1
  (2, 8)	1
  (2, 3)	1
  (2, 6)	1
  (2, 0)	1
  (2, 7)	1
  (2, 4)	1
  (3, 8)	1
  (3, 3)	1
  (3, 6)	1
  (3, 2)	2
  (3, 1)	1
(4, 9)


In [14]:
from sklearn.feature_extraction.text import HashingVectorizer
corpus=["this is the first document.",
       "this is the second document.",
       "and this is the third one.",
       "is this the first first document?"]
cvectorizer=HashingVectorizer()
x=cvectorizer.fit_transform (corpus)
#print(cvectorizer.vocabulary_)
print(x)
print(x.shape)

  (0, 144749)	0.4472135954999579
  (0, 170062)	0.4472135954999579
  (0, 286878)	-0.4472135954999579
  (0, 351664)	-0.4472135954999579
  (0, 989160)	-0.4472135954999579
  (1, 144749)	0.4472135954999579
  (1, 170062)	0.4472135954999579
  (1, 286878)	-0.4472135954999579
  (1, 351664)	-0.4472135954999579
  (1, 544379)	0.4472135954999579
  (2, 144749)	0.4082482904638631
  (2, 170062)	0.4082482904638631
  (2, 178949)	0.4082482904638631
  (2, 180525)	-0.4082482904638631
  (2, 286878)	-0.4082482904638631
  (2, 948532)	-0.4082482904638631
  (3, 144749)	0.35355339059327373
  (3, 170062)	0.35355339059327373
  (3, 286878)	-0.35355339059327373
  (3, 351664)	-0.35355339059327373
  (3, 989160)	-0.7071067811865475
(4, 1048576)


In [15]:
from sklearn.feature_extraction.text import HashingVectorizer
corpus=["this is the first document.",
       "this is the second document.",
       "and this is the third one.",
       "is this the first first document?"]
cvectorizer=HashingVectorizer(n_features=2**10,norm=None,alternate_sign=True)
x=cvectorizer.fit_transform (corpus)
#print(cvectorizer.vocabulary_)
print(x)
print(x.shape)

  (0, 78)	1.0
  (0, 158)	-1.0
  (0, 365)	1.0
  (0, 432)	-1.0
  (0, 1000)	-1.0
  (1, 78)	1.0
  (1, 158)	-1.0
  (1, 365)	1.0
  (1, 432)	-1.0
  (1, 635)	1.0
  (2, 78)	1.0
  (2, 158)	-1.0
  (2, 301)	-1.0
  (2, 308)	-1.0
  (2, 365)	1.0
  (2, 773)	1.0
  (3, 78)	1.0
  (3, 158)	-1.0
  (3, 365)	1.0
  (3, 432)	-1.0
  (3, 1000)	-2.0
(4, 1024)


In [16]:
#linear regression
#y=mx+c
#m slop x independent variable and y is dependent variable 
from sklearn import linear_model
import pandas as pd
df=pd.DataFrame({'point':[1,2,3,4,5],
                 'age':[10,23,34,78,89]})
print(df)
reg=linear_model.LinearRegression()
reg.fit(df[['age']],df.point)#age-independent,point-dependent

   point  age
0      1   10
1      2   23
2      3   34
3      4   78
4      5   89


LinearRegression()

In [17]:
m=reg.coef_
m

array([0.04401918])

In [18]:
c=reg.intercept_
c

0.9399024551541704

In [19]:
y=m*10+c
y

array([1.38009424])

In [20]:
reg.predict([[10]])

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1.38009424])