In [1]:
#numpy-numerical python library
#multidimentional array
#methametical and logical operation
import numpy as np
a=np.array([1,2,3])
b=np.array([[2,3],[4,5]])
c=np.array([1,2,3],dtype=complex)
print(a)
print(b)
print(c)

[1 2 3]
[[2 3]
 [4 5]]
[1.+0.j 2.+0.j 3.+0.j]


In [2]:
#attributes of np array
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(type(arr))
print(arr.ndim)#dimention of array
print(arr.shape)
print(arr.size)
print(arr.dtype)#array element datatype

<class 'numpy.ndarray'>
2
(2, 4)
8
int32


In [3]:
#array creation techniques
import numpy as np
n=np.array([1,3,2])
d=np.full((3,3),6,dtype='float')
print("an array initiated with all 6:",d)

an array initiated with all 6: [[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [4]:
#multidimentional array
a=np.array([[1,2,4],[5,8,7]],dtype='float')
a

array([[1., 2., 4.],
       [5., 8., 7.]])

In [5]:
print(a[1][2])
print(a[1,2])

7.0
7.0


In [6]:
#random value
e=np.random.random((2,2))

In [7]:
e

array([[0.68251819, 0.931071  ],
       [0.41537709, 0.53537788]])

In [8]:
f=np.random.rand(4,3)
f

array([[0.27950507, 0.31832978, 0.74276573],
       [0.22191896, 0.20996469, 0.02607239],
       [0.45231375, 0.08561116, 0.08332358],
       [0.15542422, 0.0377212 , 0.70282801]])

In [9]:
g=np.random.randint(low=5,high=20,size=10)
g

array([16, 13, 15, 12,  8, 17, 13,  8,  9, 17])

In [2]:
import numpy as np
c=np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
d=np.ones((3,4))
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
import numpy as np
a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [7]:
c=np.arange(10,24,2)
print(c)

[10 12 14 16 18 20 22]


In [9]:
import numpy as np
a=np.arange(24)
#new reshape
d=a.reshape(2,3,4)
print(d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [11]:
#linspace = return numbers over a specified inner values
g=np.linspace(2,10,4)
print(g)

[ 2.          4.66666667  7.33333333 10.        ]


In [13]:
#flatten
x=a.flatten()
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
